core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from bot.bot import webhook


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/accounts/', include('account.urls')),
    path('api/v1/courses/', include('course.urls')),
    path('api/v1/bot/', webhook),
    path('', include('home.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from course.views.course import CourseListView


urlpatterns = [
    path('courses/', CourseListView.as_view())
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('team/', views.team, name='team'),
    path('courses/', views.courses, name='courses'),
]

course/models/category.py
from django.db import models
from core.utils.base_model import BaseModel


class Category(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

course/models/course.py
from django.db import models
from core.utils.base_model import BaseModel


class Group(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    teacher = models.ForeignKey("account.User", on_delete=models.CASCADE, null=True)
    students = models.ManyToManyField("account.User", related_name="course_groups")
    def __str__(self) -> str:
        return self.name


class ExamGrade(BaseModel):
    name = models.CharField(max_length=255)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='exam_grades')
    date = models.DateField()
    grades_photo = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.name} - {self.group}  ({self.date})"


class Course(BaseModel):
    name = models.CharField(max_length=255)
    teacher = models.ForeignKey(
        'account.User', 
        on_delete=models.SET_NULL, 
        related_name='courses', 
        null=True
        )
    info = models.TextField(blank=True, null=True)
    category = models.ForeignKey('course.Category', on_delete=models.CASCADE, related_name='courses')
    
    def __str__(self) -> str:
        return self.name

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms

from account.models import User
from course.models import Course

input_style = 'width: 90%; margin: 0 auto; padding: 8px; border: 1px solid #ccc; border-radius: 4px'
class UserForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ism', 'style': input_style}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Familiya', 'style': input_style}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '+998', 'style': input_style}))
    courses = forms.ModelChoiceField(
        label="Kurslar",
        queryset=Course.objects.all(),
        widget=forms.Select(attrs={'class': 'custom-class', 'style': input_style}),
    )

course/views/course.py
from django.views.generic import ListView
from course.models.course import Course


class CourseListView(ListView):
    model = Course
    context_object_name = 'course_list'
    template_name = 'course/course_list.html'

home/views.py
from django.shortcuts import render, redirect
from core.utils.alfa_crm import create_lead
from .forms import UserForm


def index(request):
    if request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            course_name = form.cleaned_data['courses']
            create_lead(
                name=f"{first_name} {last_name}",
                phone=phone_number,
                note=course_name.name
            )
            return redirect("home:index")
    else:
        form = UserForm()
    return render(request, "home/index.html", context={"title": "test title", "form": form})


def about(request):
    return render(request, "home/about.html")


def courses(request):
    if request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            course_name = form.cleaned_data['courses']

            create_lead(
                name=f"{first_name} {last_name}",
                phone=phone_number,
                note=course_name.name
            )
            return redirect("home:index")
    else:
        form = UserForm()
    return render(request, "home/courses.html", context={"title": "test title", "form": form})


def team(request):
    return render(request, "home/team.html")

home/templates/home/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Callan Haqida</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo-gold.png' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
      integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <script defer src="{% static 'js/nav.js' %}"></script>
    <script defer src="{% static 'js/hero.js' %}"></script>
    <script defer src="{% static 'js/courses.js' %}"></script>
    <script defer src="{% static 'js/result.js' %}"></script>
    <script defer src="{% static 'js/main.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/nav.css' %}" />
    <link rel="stylesheet" href="{% static 'css/hero.css' %}" />
    <link rel="stylesheet" href="{% static 'css/about.css' %}" />
    <link rel="stylesheet" href="{% static 'css/courses.css' %}" />
    <link rel="stylesheet" href="{% static 'css/result.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/css/swiper.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    />
  </head>
  <body>
    <div class="container_ m-0 p-0">
      <div class="navigation">
        <div class="nav-container">
          <div class="brand">
            <a href="index.html" class="flexbox-center"
              ><img class="logo" src="{% static 'images/logo-gold.png' %}" alt="logo" /> Callan
              Education</a
            >
          </div>
          <nav>
            <div class="nav-mobile">
              <a id="nav-toggle" href="#!"><span></span></a>
            </div>

            <ul class="nav-list">
              <li><a href="{% url 'home:index' %}">Bosh sahifa</a></li>
              <li><a href="{% url 'home:about' %}">Biz haqimizda</a></li>
              <li>
                <a href="#!">Kurslar</a>
                <ul class="nav-dropdown white">
                  <li><a href="{% url 'home:courses' %}#odatiy">Odatiy</a></li>

                  <li><a href="{% url 'home:courses' %}#induvidual">Induvidual</a></li>
                </ul>
              </li>
              <li><a href="{% url 'home:team' %}">Natijalar</a></li>
              <li>
                <a class="highlited" href="{% url 'home:index' %}#registration">Kursga yozilish</a>
              </li>
              <li>
                <a class="highlited" href="tel:+998971291111"><i class="fa-solid fa-phone"></i> (97) 129 11 11</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- !end of the navbar -->
      <section class="about section bd-container" id="about">
        <h2 class="section-title title">Callan haqida</h2>

        <div class="about__container bd-grid">
          <div class="about__data bd-grid">
            <p class="about__description">
              <span>Callan Education Group<br /></span>Jamoamiz bilan birgalikda
              3 yil mobaynida Dasturlash, Ingliz tili, Rus tili, Arab tili va
              ko'plab boshqa fanlardan ta'lim berib kelmoqdamiz. Bixning
              markazimizda ilm olgan talabalar, o'zlarining maqsadlariga
              erishmoqdalar.
            </p>

            <div>
              <span class="about__number">3+</span>
              <span class="about__achievement">Yil Tajriba</span>
            </div>

            <div>
              <span class="about__number">1000+</span>
              <span class="about__achievement"
                >Kurslarni tamomlagan talabalar</span
              >
            </div>

            <div>
              <span class="about__number">600+</span>
              <span class="about__achievement"
                >Hozirgi taqsil olayotganlar</span
              >
            </div>
          </div>

          <img src="{% static 'images/logo-gold.png' %}" alt="" class="about__img" />
        </div>
      </section>

      <!-- !end of the courses -->

      <footer class="footer-section">
        <div class="container">
          <div class="footer-cta pt-5 pb-5">
            <div class="row">
              <div class="col-xl-4 col-md-4 mb-30">
                <div class="single-cta">
                  <i class="fas fa-map-marker-alt"></i>
                  <div class="cta-text">
                    <h4>Mazil</h4>
                    <span>1010 Qo'qon shahar, Hamza 12-uy</span>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-md-4 mb-30">
                <div class="single-cta">
                  <i class="fas fa-phone"></i>
                  <div class="cta-text">
                    <h4>Sim qoqing</h4>
                    <span>+998(97) 129 11 11</span>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-md-4 mb-30">
                <div class="single-cta">
                  <i class="far fa-envelope-open"></i>
                  <div class="cta-text">
                    <h4>E-pochta manzili</h4>
                    <span>callaneducatio.uz@gmail.com</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="footer-content pt-5 pb-5">
            <div class="row">
              <div class="col-xl-4 col-lg-4 mb-50">
                <div class="footer-widget">
                  <div class="footer-logo">
                    <a href="{% url 'home:index' %}"><img
                        src="{% static 'images/logo-gold.png' %}"
                        class="img-fluid"
                        alt="logo"
                      />
                      <div class="title">
                        <h1 style="color: var(--gold)">CallanEdu</h1>
                      </div></a
                    >
                  </div>
                  <div class="footer-text">
                    <p>
                      Kurslarimiz haqida batafsil ma'lumot va ko'rsatmalar olish
                      uchun berilgan kontaktga telefon qilishingizni so'raymiz!
                    </p>
                  </div>
                  <div class="footer-social-icon">
                    <span>Ijtimoiy tarmoqlarimiz</span>
                    <a href="#"><i class="fab fa-facebook-f google-bg"></i></a>
                    <a href="#"><i class="fab fa-instagram twitter-bg"></i></a>
                    <a href="#"><i class="fab fa-telegram google-bg"></i></a>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-lg-4 col-md-6 mb-30">
                <div class="footer-widget">
                  <div class="footer-widget-heading">
                    <h3>Foydali linklar</h3>
                  </div>
                  <ul>
                    <li><a href="#">Bosh sahifa</a></li>
                    <li><a href="#">Haqimizda</a></li>
                    <li><a href="#">Tariflar</a></li>
                    <li><a href="#">Narxlar</a></li>
                    <li><a href="#">Kontakt</a></li>
                    <li><a href="#">Kurslar</a></li>
                    <li><a href="#">Natijalar</a></li>
                    <li><a href="#">Chegirmalar</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-xl-4 col-lg-4 col-md-6 mb-50">
                <div class="footer-widget">
                  <div class="footer-widget-heading">
                    <h3>Xabardor bo'ling</h3>
                  </div>
                  <div class="footer-text mb-25">
                    <p>Email manzilingizni yozib qoldiring!</p>
                  </div>
                  <div class="subscribe-form">
                    <form action="#">
                      <input type="text" placeholder="Email Address" />
                      <button><i class="fab fa-telegram-plane"></i></button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="copyright-area">
          <div class="container">
            <div class="row">
              <div class="col-xl-6 col-lg-6 text-center text-lg-left">
                <div class="copyright-text">
                  <p>
                    Mualliflik huquqi asosida &copy; 2024, barcha huquqlar
                    himoyalangan
                    <a
                      href="https://new.birdarcha.uz/document/b0fcf782-b48b-4add-9326-7da6b4cadde0"
                      >Callan Education</a
                    >
                  </p>
                </div>
              </div>
              <div class="col-xl-6 col-lg-6 d-none d-lg-block text-right">
                <div class="footer-menu">
                  <ul>
                    <li><a href="#">Bosh sahifa</a></li>
                    <li><a href="#">Kelishuvlar</a></li>
                    <li><a href="#">Xavfsizlik</a></li>
                    <li><a href="#">Qoidalar</a></li>
                    <li><a href="#">Bog'lanish</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.5/jquery.bxslider.js"></script>
  </body>
</html>